name: Push to FTP
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.4.5
        with:
          host: 'ftp.cluster030.hosting.ovh.net'
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }} 
          localDir: 'site'
          remoteDir: '/home/agutiek/www/'